version: '3'
services:
  app:
    container_name: node
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
